Change ListViewCard observables to PublishSubjects
Snagajob/Rx.Widgets pull request #2
Opened 2017-01-20 15:15 UTC by CoreyHorn

These changes allow a consumer of the API to subscribe to the Observables surfaced by ListViewCard at any point. Previous implementation could lead to NPEs being thrown when attempting to subscribe too early.

2017-01-20 15:53 UTC, mdesoto commented
I don't think this is the right approach. We have naked subscriptions that cannot be unsubscribed from, and we're creating one for each item. Which isn't necessary either.

2017-01-26 22:25 UTC, mdesoto requested changes

2017-01-26 22:25 UTC, mdesoto commented on library/src/main/java/io/andref/rx/widgets/ListViewCard.java
> +                .subscribe(mButtonClicks);
Don't like the naked subscriptions buried in the view. Need to make sure they get unsubscribed from. Maybe `takeUntil`, `RxView.detaches()`. Or something like that.

2017-01-26 22:25 UTC, mdesoto commented on library/src/main/java/io/andref/rx/widgets/ListViewCard.java
> +                    .subscribe(mItemClicks);
Same as above. Plus we're creating a subscription for every view.  Seems unnecessary.

2017-01-26 22:25 UTC, mdesoto commented on library/src/main/java/io/andref/rx/widgets/ListViewCard.java
> +                        .subscribe(mIconClicks);
Same as above (x2).

2017-01-31 18:44 UTC, CoreyHorn commented on library/src/main/java/io/andref/rx/widgets/ListViewCard.java
> +                    .subscribe(mItemClicks);
If we want to not have subscriptions for every view, we will need to switch to using the adapter pattern for this view. Any work we do to support managing multiple views within this one would just be duplicating that pattern.

2017-01-31 18:45 UTC, CoreyHorn commented on library/src/main/java/io/andref/rx/widgets/ListViewCard.java
> +                .subscribe(mButtonClicks);
Good point. Doing that now.

2017-01-31 18:53 UTC, mdesoto commented on library/src/main/java/io/andref/rx/widgets/ListViewCard.java
> +                    .subscribe(mItemClicks);
You should be able to merge all the observables and subscribe to that.

2017-01-31 18:59 UTC, mdesoto requested changes

2017-01-31 18:59 UTC, mdesoto commented on library/src/main/java/io/andref/rx/widgets/ListViewCard.java
> +    }
Still don't think we have the right answer here. We need to drive/respond to this view in the consuming activity/fragment, and that lifecycle won't necessarily match window state.

If we're going to subscribe in the view, I think `takeUntil(view detaches)` is more appropriate.

2017-02-01 23:21 UTC, mdesoto commented
OK! I refactored this a bit. And added the ability to manipulate the view (show/hide button, add/remove items). Frankly those should be UI tests.

Anyway, have a look. See if there's anything I missed.

2017-02-02 14:46 UTC, CoreyHorn commented on library/src/main/java/io/andref/rx/widgets/ListViewCard.java
>      private Observable<Void> mButtonClicks;
Any reason you converted this back to a plain Observable as opposed to a PublishSubject? 

Using a PublishSubject allows subscribing at any point and seems to be good practice for surfacing view bindings as observables.

2017-02-02 14:49 UTC, CoreyHorn commented on library/src/main/java/io/andref/rx/widgets/ListViewCard.java
>      private Observable<Void> mButtonClicks;
After removing all views and adding another, none of the clicks on the newly added views are being recognized

2017-02-02 16:48 UTC, mdesoto commented on library/src/main/java/io/andref/rx/widgets/ListViewCard.java
>      private Observable<Void> mButtonClicks;
The button is never removed, so there's no need to wrap it's observable in a publish subject.

2017-02-02 16:54 UTC, CoreyHorn commented on library/src/main/java/io/andref/rx/widgets/ListViewCard.java
>      private Observable<Void> mButtonClicks;
The problem is that we are exposing a null Observable. Attempting to subscribe or call operators on that Observable will cause NPEs if it hasn't been initialized yet. I usually fix that by exposing PublishSubjects. 

However, we may also be able to fix that by initializing the Observables as Observable.empty().

2017-02-07 15:42 UTC, merged